name: Trigger auto deployment for break-the-budget

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/break-the-budget-AutoDeployTrigger-05eefc63-6a3e-414c-b4c9-3862002a1a17.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.BREAKTHEBUDGET_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.BREAKTHEBUDGET_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.BREAKTHEBUDGET_AZURE_SUBSCRIPTION_ID }}

      - name: Create '.env' file
        run: |
            touch .env
            echo DB_CONNECT_URL="${{ secrets.DB_CONNECT_URL }}" >> .env
            echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> .env
            echo HASH_SALT=${{ secrets.HASH_SALT }} >> .env
            cat .env

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: linuxwebapp.azurecr.io
          registryUsername: ${{ secrets.BREAKTHEBUDGET_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.BREAKTHEBUDGET_REGISTRY_PASSWORD }}
          containerAppName: break-the-budget
          resourceGroup: QA_Web_App
          imageToBuild: linuxwebapp.azurecr.io/break-the-budget:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_






